"""Merge ps2_analyzer output with our hand-maintained config/roadtrip.base.toml.

Rules:
  [general] scalars in base override the analyzer.
  [general] stubs / skip / entry_points: union (base entries win on name collision).
  [general] drop_stubs / drop_entry_points: names removed from the analyzer lists.
  [mmio]: union, base wins.
  [[jump_tables.table]]: base tables replace analyzer tables with the same address.
  [patches]: taken from base.
The result only contains addresses and names (no game code), so it is committed.
"""
from __future__ import annotations

import os
import tomllib
from pathlib import Path
from typing import Any

LIST_KEYS = ("stubs", "skip", "entry_points")
INFO_SECTIONS = ("performance",)  # analyzer diagnostics, not read by ps2_recomp


def _name(entry: str) -> str:
    return entry.split("@", 1)[0]


def _union(base: list[str], extra: list[str], drop: set[str]) -> list[str]:
    seen = {_name(e) for e in extra}
    out = [e for e in base if _name(e) not in seen and _name(e) not in drop]
    return out + extra


def merge(analyzer: dict[str, Any], base: dict[str, Any]) -> dict[str, Any]:
    out: dict[str, Any] = {k: v for k, v in analyzer.items() if k not in INFO_SECTIONS}
    gen = dict(out.get("general", {}))
    bgen = dict(base.get("general", {}))
    for key in LIST_KEYS:
        drop = set(bgen.pop(f"drop_{key}", []))
        gen[key] = _union(gen.get(key, []), bgen.pop(key, []), drop)
    gen.update(bgen)
    out["general"] = gen

    out["mmio"] = {**out.get("mmio", {}), **base.get("mmio", {})}

    tables = {t["address"].lower(): t for t in out.get("jump_tables", {}).get("table", [])}
    for t in base.get("jump_tables", {}).get("table", []):
        tables[t["address"].lower()] = t
    out["jump_tables"] = {"table": sorted(tables.values(), key=lambda t: int(t["address"], 16))}

    if "patches" in base:
        out["patches"] = base["patches"]
    return out


# ----------------------------------------------------------------- tiny TOML writer

def _val(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, str):
        return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'
    if isinstance(v, dict):
        return "{ " + ", ".join(f"{k} = {_val(x)}" for k, x in v.items()) + " }"
    if isinstance(v, list):
        if not v:
            return "[]"
        return "[\n" + "".join(f"  {_val(x)},\n" for x in v) + "]"
    raise TypeError(type(v))


def _key(k: str) -> str:
    return k if k.replace("_", "").isalnum() else _val(k)


def dumps(doc: dict[str, Any]) -> str:
    lines = ["# GENERATED by scripts/pipeline.py analyze -- edit config/roadtrip.base.toml instead.", ""]
    for section, body in doc.items():
        if section == "jump_tables":
            lines.append("[jump_tables]")
            for t in body["table"]:
                lines.append("[[jump_tables.table]]")
                lines += [f"{_key(k)} = {_val(v)}" for k, v in t.items()]
                lines.append("")
            continue
        lines.append(f"[{section}]")
        lines += [f"{_key(k)} = {_val(v)}" for k, v in body.items()]
        lines.append("")
    return "\n".join(lines)


def merge_config(analyzer_toml: Path, base_toml: Path, out_toml: Path, *, elf_path: Path,
                 output_dir: Path, extra_entry_points: list[str] | None = None) -> None:
    analyzer = tomllib.loads(analyzer_toml.read_text())
    if extra_entry_points:
        gen = analyzer.setdefault("general", {})
        known = {int(e.split("@", 1)[1], 16) for e in gen.get("entry_points", []) + gen.get("stubs", []) if "@" in e}
        gen["entry_points"] = gen.get("entry_points", []) + [
            e for e in extra_entry_points if int(e.split("@", 1)[1], 16) not in known]
    base = tomllib.loads(base_toml.read_text()) if base_toml.exists() else {}
    doc = merge(analyzer, base)
    # Paths are written relative to the repo root (ps2_recomp runs with cwd = repo root).
    root = out_toml.resolve().parent.parent
    doc["general"]["input"] = os.path.relpath(elf_path.resolve(), root)
    doc["general"]["output"] = os.path.relpath(output_dir.resolve(), root) + "/"
    out_toml.write_text(dumps(doc))
    g = doc["general"]
    print(f"   {out_toml}: {len(g['stubs'])} stubs, {len(g['entry_points'])} entry points, "
          f"{len(g['skip'])} skips, {len(doc['mmio'])} mmio, {len(doc['jump_tables']['table'])} jump tables")
